[env]
TERM = "screen-256color"

[general]
live_config_reload = true

[terminal]

[terminal.shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/bash"
args = [
    "--login",
    "-x",
    "-c",
    "/home/linuxbrew/.linuxbrew/bin/tmux attach || /home/linuxbrew/.linuxbrew/bin/tmux"
]

[window]
decorations = "none"
opacity = 1
option_as_alt = "Both"
startup_mode = "Maximized"

[scrolling]
history = 10000
multiplier = 3

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Underline"

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
