[env]
TERM = "tmux-256color"

[general]
live_config_reload = true

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 1
decorations = "None"
option_as_alt = "Both"
startup_mode = "Maximized"

[scrolling]
history = 50000
multiplier = 3

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Underline"

[font]
size = 9
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"
# style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"
