semi: true
tabWidth: 4
printWidth: 100
trailingComma: "all"
importOrder: ["^~/(.*)$"]
importOrderSeparation: true
importOrderSortSpecifiers: true
plugins:
  - "prettier-plugin-tailwindcss"
  - "prettier-plugin-sort-json"
  - "@trivago/prettier-plugin-sort-imports"
overrides:
  - files:
      - "*.yml"
      - "*.yaml"
    options:
      tabWidth: 2
