-- vim.lsp.set_log_level('debug')
require('jsgv.plugins')
require('jsgv.setup')
require('jsgv.lsp')
require('jsgv.plugins.git-worktree')
require('jsgv.plugins.nvim-tree')
require('jsgv.plugins.nvim-treesitter')
require('jsgv.plugins.telescope')
require('jsgv.plugins.vim-commentary')
require('jsgv.plugins.vim-go')
require('jsgv.plugins.vim-prettier')
